# Generated by Django 2.1.7 on 2019-04-01 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='corpus_url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
